  DROP TABLE IF EXISTS statistics;

  CREATE TABLE IF NOT EXISTS statistics (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  app VARCHAR(40),
  uri VARCHAR(500),
  ip VARCHAR(40),
  timestamp_hit TIMESTAMP WITHOUT TIME ZONE NOT NULL);